name: Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      # Install dependencies.
      - uses: actions/cache@v3
        name: Python cache with dependencies.
        id: python-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ matrix.os }}-${{ matrix.python }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev_requirements.pip') }}
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.pip
          pip list

      # Build and Upload.
      - name: Build sdist and wheel.
        run: |
          pip install wheel
          rm -rf build dist *.egg-info
          python setup.py sdist bdist_wheel
      # Check.
      - name: Check dist with twine
        run: |
          pip install twine
          twine check dist/*
      - name: Upload sdist and wheel.
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: limesurveyrc2api--on-${{ matrix.os }}--py${{ matrix.python }}
          path: ${{ github.workspace }}/dist/limesurveyrc2api*
